//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKevin13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewing
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int PropertyForRentId { get; set; }
        public System.DateTime ViewDate { get; set; }
        public string CommentsGiven { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PropertyForRent PropertyForRent { get; set; }
    }
}
